### ISSUE TITLE
ProceduralPass-Java every passwords shows all logins and password missing?

### ISSUE THREAD

**Issue by Perflyst** [duudl3/proceduralpass#2]
OS: Linux Ubuntu 16.04
ProceduralPass Version: v1.4.1 Java Edition

I can type any password to get the logins.

Also I cannot set a password if I add a login. Only username and website can be set.

**Comment by duudl3** [comment]
Do you know how the program works? You don't set a password at all. It generates a password procedurally every time you login. If you set the master password to the same thing every time, you get the same passwords every time. If you enter the master password differently, the program will generate an entirely new set of passwords, so if you enter it wrong, just relaunch and enter your password correctly.

That is literally the whole point of the program.

This isn't a bug, it's literally the program.

**Comment by Perflyst** [comment]
So if I wanna use this program I have to change all my passwords first to the generated ones?
